export { default as Template1 } from './Template1'
export { default as Template2 } from './Template2'
export { default as Template3 } from './Template3'
export { default as Template4 } from './Template4'
export { default as Template5 } from './Template5'